chat-zen:
  security:
    # Security认证白名单
    permit-all-path:
      - /http-test/**
      - /auth/**
      - /ws/**
      - /user/login
      - /user/register

spring:
  profiles:
    # 加载不同环境的配置文件
    active: dev


