server:
  port: 8888
chat-zen:
  jwt:
    key: xianlin
    expire: 2
# 开发环境配置
spring:
  mail:
    host: smtp.163.com
    username: 15653674386@163.com
    password: PITHQADAOMQATXRD
    protocol: smtp
    port: 465
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail:
        smtp:
          ssl:
            enable: true
            trust: '*'
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  
  rabbitmq:
    addresses: 121.41.122.33
    port: 5672
    username: rabbitmq
    password: rabbitmq_mY3nw4
    virtual-host: /
  # 配置MySql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 设置驱动程序
    url: jdbc:mysql://121.41.122.33:3306/chat_zen?useSSL=false&allowPublicKeyRetrieval=true # 设置数据库
    username: root  # 数据库用户名
    password: mysql_mY3nw4  # 数据库密码
  # 配置Redis数据源
  data:
    redis:
      host: 121.41.122.33 # 连接地址
      port: 6379 # 连接端口
      password: redis_6pGn3p
      jedis:
        pool:
          max-active: 8 # 最大连接数
          max-wait: -1 # 最大阻塞等待时间(-1表示无限制)
          max-idle: 8 # 最大空闲
          min-idle: 0 # 最小空闲
  security:
    jwt:
      key: 'xianlin'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
  devtools:
    restart:
      enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  config: classpath:logback/prod-logback.xml # 配置LogBack日志框架配文件路径