server:
  # 设置服务启动端口
  port: 8888
chat-zen:
  jwt:
    key: xianlin
    expire: 2
spring:
  profiles:
    active: '@environment@'
  devtools:
    restart:
      enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn
