server:
  port: 8080

chat-zen:
  security:
    # Security认证白名单
    permit-all-path:
      - /http-test/**
      - /auth/**
      - /ws/**
      - /user/add/**
  jwt:
    # jwt加密key
    key: chatzen-key
    expiration: 172800000 # 48 hour - *ms

spring:
  # 配置Mysql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chatzen?useSSL=false&allowPublicKeyRetrieval=true # 设置数据库
    username: root  # 数据库用户名
    password: root  # 数据库密码
  # 配置Redis数据源
  data:
    redis:
      host: 127.0.0.1 # 连接地址
      port: 6379 # 连接端口
      password: redis_xlpass