# 开发环境配置
spring:
  mail:
    host: smtp.163.com
    username: 15653674386@163.com
    password: PITHQADAOMQATXRD
    protocol: smtp
  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  # 配置MySql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 设置驱动程序
    url: jdbc:mysql://localhost:3306/chat_zen?useSSL=false # 设置数据库
    username: root  # 数据库用户名
    password: root  # 数据库密码
  # 配置Redis数据源
  data:
    redis:
      host: 127.0.0.1 # 连接地址
      port: 6379 # 连接端口
      jedis:
        pool:
          max-active: 8 # 最大连接数
          max-wait: -1 # 最大阻塞等待时间(-1表示无限制)
          max-idle: 8 # 最大空闲
          min-idle: 0 # 最小空闲
  security:
    jwt:
      key: 'xianlin'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'

logging:
  config: classpath:logback/dev-logback.xml # 配置LogBack日志框架配文件路径