server:
  port: 8080

chat-zen:
  jwt:
    key: chatzen-key
    expiration: 3600000 # 1 hour - 3600000ms

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.122.33:3306/chatzen?useSSL=false&allowPublicKeyRetrieval=true # 设置数据库
    username: chat_zen  # 数据库用户名
    password: ieFiFH2WAwdEYQMi  # 数据库密码