spring:
  # 配置Mysql数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/chatzen?useSSL=false&allowPublicKeyRetrieval=true # 设置数据库
    username: root  # 数据库用户名
    password: ${MYSQL_PASSWORD}  # 数据库密码
  # 配置Redis数据源
  data:
    redis:
      host: ${DB_HOST} # 连接地址
      port: 6379 # 连接端口
      password: ${REDIS_PASSWORD}
  flyway:
    # 启用或禁用 Flyway, 自动管理数据库表结构
    enabled: true


